"""Add character type, lore fields, and NPC library support.

Revision ID: 20260624_07
Revises: 20260620_06
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = "20260624_07"
down_revision = "20260620_06"
branch_labels = None
depends_on = None


def _columns(table: str) -> set[str]:
    return {column["name"] for column in sa.inspect(op.get_bind()).get_columns(table)}


def _add_column(table: str, column: sa.Column) -> None:
    if column.name not in _columns(table):
        op.add_column(table, column)


def _add_index(table: str, name: str, columns: list[str]) -> None:
    if name not in _indexes(table):
        op.create_index(name, table, columns, unique=False)


def _indexes(table: str) -> set[str]:
    return {index["name"] for index in sa.inspect(op.get_bind()).get_indexes(table)}


def upgrade() -> None:
    bind = op.get_bind()

    # Add new columns (safe on both SQLite and PostgreSQL).
    for column in (
        sa.Column("character_type", sa.String(), nullable=False, server_default="pc"),
        sa.Column("race", sa.String(), nullable=True),
        sa.Column("background", sa.String(), nullable=True),
        sa.Column("alignment", sa.String(), nullable=True),
        sa.Column("personality_traits", sa.Text(), nullable=True),
        sa.Column("ideals", sa.Text(), nullable=True),
        sa.Column("bonds", sa.Text(), nullable=True),
        sa.Column("flaws", sa.Text(), nullable=True),
        sa.Column("appearance", sa.Text(), nullable=True),
        sa.Column("backstory", sa.Text(), nullable=True),
        sa.Column("goals", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("portrait_url", sa.String(), nullable=True),
    ):
        _add_column("characters", column)

    _add_index("characters", "ix_characters_character_type", ["character_type"])

    # Make campaign_id nullable — SQLite requires table rebuild.
    if bind.dialect.name == "sqlite":
        # Discover the actual FK constraint name (auto-generated by SQLAlchemy).
        inspector = sa.inspect(bind)
        fk_name = None
        for fk in inspector.get_foreign_keys("characters"):
            if fk.get("referred_table") == "campaigns":
                fk_name = fk["name"]
                break

        with op.batch_alter_table("characters") as batch_op:
            batch_op.alter_column("campaign_id", nullable=True)
            # Change campaign FK from CASCADE to SET NULL.
            if fk_name:
                batch_op.drop_constraint(fk_name, type_="foreignkey")
            batch_op.create_foreign_key(
                "fk_characters_campaign_id_campaigns",
                "campaigns",
                ["campaign_id"],
                ["id"],
                ondelete="SET NULL",
            )
    else:
        op.alter_column("characters", "campaign_id", nullable=True)
        op.drop_constraint(
            "fk_characters_campaign_id_campaigns", "characters", type_="foreignkey"
        )
        op.create_foreign_key(
            "fk_characters_campaign_id_campaigns",
            "characters",
            "campaigns",
            ["campaign_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # Bump schema_version for existing characters so the model default matches.
    op.execute("UPDATE characters SET schema_version = 2")


def downgrade() -> None:
    bind = op.get_bind()

    if bind.dialect.name == "sqlite":
        inspector = sa.inspect(bind)
        fk_name = None
        for fk in inspector.get_foreign_keys("characters"):
            if fk.get("referred_table") == "campaigns":
                fk_name = fk["name"]
                break

        with op.batch_alter_table("characters") as batch_op:
            batch_op.alter_column("campaign_id", nullable=False)
            if fk_name:
                batch_op.drop_constraint(fk_name, type_="foreignkey")
            batch_op.create_foreign_key(
                "fk_characters_campaign_id_campaigns",
                "campaigns",
                ["campaign_id"],
                ["id"],
                ondelete="CASCADE",
            )
    else:
        op.alter_column("characters", "campaign_id", nullable=False)
        op.drop_constraint(
            "fk_characters_campaign_id_campaigns", "characters", type_="foreignkey"
        )
        op.create_foreign_key(
            "fk_characters_campaign_id_campaigns",
            "characters",
            "campaigns",
            ["campaign_id"],
            ["id"],
            ondelete="CASCADE",
        )

    for column_name in (
        "character_type", "race", "background", "alignment",
        "personality_traits", "ideals", "bonds", "flaws",
        "appearance", "backstory", "goals", "notes", "portrait_url",
    ):
        if column_name in _columns("characters"):
            op.drop_column("characters", column_name)

    if "ix_characters_character_type" in _indexes("characters"):
        op.drop_index("ix_characters_character_type", table_name="characters")
